apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "student-risk-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "student-risk-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "student-risk-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "student-risk-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: student-risk-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
