"""Training stage for a reproducible Decision Tree pipeline."""

import os
import joblib
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeClassifier

PROCESSED_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "processed")
MODELS_DIR = os.path.join(os.path.dirname(__file__), "..", "models")

PIPELINE_FILE = "decision_tree_pipeline.pkl"
FEATURE_COLUMNS_FILE = "feature_columns.pkl"
RANDOM_SEED = 42
MAX_DEPTH = 5


def load_processed_data(processed_dir: str) -> tuple[pd.DataFrame, pd.Series]:
    """Load pre-split training set generated by preprocess.py."""
    X_train = pd.read_csv(os.path.join(processed_dir, "X_train.csv"))
    y_train = pd.read_csv(os.path.join(processed_dir, "y_train.csv")).squeeze()
    return X_train, y_train


def build_pipeline(X_train: pd.DataFrame) -> Pipeline:
    """Build preprocessing + Decision Tree classifier pipeline."""
    categorical_cols = X_train.select_dtypes(include=["object", "category"]).columns.tolist()
    numeric_cols = [c for c in X_train.columns if c not in categorical_cols]

    preprocessor = ColumnTransformer(
        transformers=[
            ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols),
            ("num", "passthrough", numeric_cols),
        ]
    )

    classifier = DecisionTreeClassifier(max_depth=MAX_DEPTH, random_state=RANDOM_SEED)

    return Pipeline([
        ("preprocessor", preprocessor),
        ("classifier", classifier),
    ])


def train(processed_dir: str = PROCESSED_DIR, models_dir: str = MODELS_DIR) -> None:
    """Train and persist the Decision Tree pipeline and feature schema."""
    os.makedirs(models_dir, exist_ok=True)

    X_train, y_train = load_processed_data(processed_dir)
    print(f"Training on {len(X_train)} samples with {X_train.shape[1]} raw features.")

    pipeline = build_pipeline(X_train)
    pipeline.fit(X_train, y_train)

    model_path = os.path.join(models_dir, PIPELINE_FILE)
    schema_path = os.path.join(models_dir, FEATURE_COLUMNS_FILE)

    joblib.dump(pipeline, model_path)
    joblib.dump(list(X_train.columns), schema_path)

    print(f"Saved pipeline artifact: {model_path}")
    print(f"Saved feature schema:    {schema_path}")


if __name__ == "__main__":
    train()
